#pragma once

/*
 * List all the TIFF images in the folder.
 */
void listTiffFiles(const fs::path &, std::vector<fs::path> &);

/*
 * Sort SPIM generated stacks in numerical order.
 * Return number of files, not generated by SPIM, removed from the list.
 */
int sortSpimStacks(std::vector<fs::path> &);